'use client';
import './globals.css'
import type { Metadata } from 'next'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import Link from 'next/link'
import {usePathname} from 'next/navigation'
import { ThemeContextProvider } from './context/theme';


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const currentRoute = usePathname();
  const csshref='block py-2 pl-3 pr-4 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent';
  const active  = csshref+' md:text-blue-700 text-white';
  const inactive = csshref+' text-gray-900';

  console.log(currentRoute); 
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="bg-white border-gray-200 dark:bg-gray-900">
          <div className="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">
            <a href="https://flowbite.com/" className="flex items-center">
              <Image src="https://flowbite.com/docs/images/logo.svg" width={100} height={100} className="h-8 mr-3" alt="Flowbite Logo" />
              <span className="self-center text-2xl font-semibold whitespace-nowrap dark:text-white">Flowbite</span>
            </a>
            <button data-collapse-toggle="navbar-default" type="button" className="inline-flex items-center p-2 w-10 h-10 justify-center text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600" aria-controls="navbar-default" aria-expanded="false">
              <span className="sr-only">Open main menu</span>
              <svg className="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 17 14">
                <path stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M1 1h15M1 7h15M1 13h15" />
              </svg>
            </button>
            <div className="hidden w-full md:block md:w-auto" id="navbar-default">
              <ul className="font-medium flex flex-col p-4 md:p-0 mt-4 border border-gray-100 rounded-lg bg-gray-50 md:flex-row md:space-x-8 md:mt-0 md:border-0 md:bg-white dark:bg-gray-800 md:dark:bg-gray-900 dark:border-gray-700">
                <li>
                  <Link href="/" className={(currentRoute ==='/') ? active : inactive} aria-current="page">Home</Link>
                </li>
                <li>
                  <Link href="/about" className={(currentRoute ==='/about') ? active : inactive}>About</Link>
                </li> 
                <li>
                  <Link href="/contact" className={(currentRoute ==='/contact') ? active : inactive}>Contact</Link>
                </li>
              </ul>
            </div>
          </div>
        </nav>
      <ThemeContextProvider>
        <section className='h-screen'>
        {children}
        </section>
      </ThemeContextProvider>
        <footer>
          <div> Ejemplo</div>
        </footer>
      </body>
    </html>
  )
}
